allow-newer: true

compiler: ghc-8.8.1

compiler-check: match-exact

extra-deps:
  - active-0.2.0.14
  - algebraic-graphs-0.4
  - bv-little-1.1.1
  - clustering-0.4.1
  - circle-packing-0.1.0.6
  - compact-0.1.0.1
  - diagrams-1.4
  - diagrams-contrib-1.4.4
  - diagrams-core-1.4.2
  - diagrams-lib-1.4.3
  - diagrams-solve-0.1.1
  - diagrams-svg-1.4.3
  - dual-tree-0.2.2.1
  - force-layout-0.4.0.6
  - graphviz-2999.20.0.3
  - lens-4.18.1
  - microlens-0.4.11.2
  - perfect-vector-shuffle-0.1.1
  - megaparsec-8.0.0
  - MissingH-1.4.2.0
  - mmark-0.0.7.2
  - monoid-extras-0.5.1
  - network-bsd-2.8.1.0
  - pretty-tree-0.1.0.0
  - svg-builder-0.1.1
  - tasty-rerun-1.1.14
  - vector-th-unbox-0.2.1.7
  - wl-pprint-text-1.2.0.0

local-bin-path: bin

require-stack-version: ">=2.1.3"

resolver: lts-15.0